import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sklep PartnerSoft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sklep.<a href="https://nextjs.org">PartnerSoft.pl</a>
        </h1>

        <p className={styles.description}>Wybierz odpowiedni program</p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Norma &rarr;</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Rodos &rarr;</h2>
            <p>
              Etiam vitae diam ex. Vestibulum sollicitudin nec magna in
              efficitur.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          PartnerSoft.pl
        </a>
      </footer>
    </div>
  )
}

export default Home
